name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend - Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

     
- name: Make mvnw executable
  working-directory: ./Backend
  run: chmod +x mvnw

- name: Build Spring Boot backend
  working-directory: ./Backend
  run: ./mvnw clean install


      # Frontend - React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Install and build homeadmin
        working-directory: ./homeadmin
        run: |
          npm install
          npm run build
